-- starter/tool-validator — config composition for the permission validator.
--
-- The classification/popup/`da` mechanism lives in `libs.tool-validator`.
-- This file is the config's policy layer. Starter ships the base policy
-- only (no extra auto-approved tools, no bash fast-paths), so it builds
-- with an empty registration. A downstream config passes its policy here,
-- e.g.:
--   require("libs.tool-validator").build {
--     auto_approve_tools = { "mirror-projects" },
--     bash_fastpaths = { function(command, read_only) ... end },
--   }
return require("libs.tool-validator").build()
